name: Python CI

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Chrome Version
        run: google-chrome --version

      - name: Install ChromeDriver
        uses: actions/checkout@v2 # This step checks out your repository

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: "88.0.4324.96"

      - name: Start ChromeDriver
        run: chromedriver --url-base=/wd/hub &

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Specify the Python version you need

      - name: Install webdriver_manager
        run: pip install webdriver_manager

      - name: Install selenium
        run: pip install selenium

      - name: Install pandas
        run: pip install pandas

      - name: Run Play.py
        run: python Play.py

      - name: Install app_store_scraper
        run: pip install app_store_scraper

      - name: Run app_store_scraping.py
        run: python app_store_scraping.py
