name: Python CI

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Chrome Version
        run: google-chrome --version

      - name: Install ChromeDriver
        uses: actions/checkout@v2 # This step checks out your repository

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: "88.0.4324.96"

      - name: Start ChromeDriver
        run: chromedriver --url-base=/wd/hub &

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Play.py
        run: python Play.py
